### PR TITLE
Add Login UI and Register UI with connection to database to add users

### PR DESCRIPTION
**Pull request by kdav108**
# Description 
Frontend:
- Added Login UI 
- Added Register UI

Backend:
- Integrated Register UI to add user to database
- Added api to patch user details
- Added api to confirm user's login credentials (integration with Login UI is still awaiting JWT implementation)

# Type of change 
- [ ] Bug fix
- [X ] New feature
- [ ] Refactoring
- [ ] Documentation 

# Problem
Needed a UI and Register Page to authenticate users and block inappropriate accesses.

# Solution description
- Add Login and Register UI using `bootstrap`
- Connected to Redux global store so that when a user registers, they're name and email is stored globally
- Add APIs for adding user, finding user credentials and patching user's data (which is probably relevant when we get to working one a Profile page)

# Tests 
No tests have been written yet, we'll target next PI hopefully

# Relevant document/ link (if any) 
N/A

# Risk
Medium

### CODE REVIEW

**Comment by kdav108** [comment]
I have added back the publications stuff, would be great if someone from Scholar can check if everything is working well with the publications.
Also, regarding the `usingRp` variable in `client/src/api/api.js`, I think it may be handy if we can set that variable through common line arguments passed into `npm run start`. Something to look into for next PI perhaps?

**Comment by kdav108** [comment]
Also, give me some time I'll fix the conflicts

**Comment by aksh0001** [comment]
> I have added back the publications stuff, would be great if someone from Scholar can check if everything is working well with the publications.
> Also, regarding the `usingRp` variable in `client/src/api/api.js`, I think it may be handy if we can set that variable through common line arguments passed into `npm run start`. Something to look into for next PI perhaps?

Yep, I’ve acknowledged that this is an inconvenience & set up a trello ticket to think up a solution for later: https://trello.com/c/Ebs7RQ2f/3-environment-variables-in-react-to-toggle-usage-of-revers-proxy-used-in-production-environment
We can definitely look into the solution you proposed

**Comment by kdav108** [comment]
All requests have been entertained, Feel free to review again :)

**Review by rpra0006 — APPROVED** [review]

**Review by aksh0001 — APPROVED** [review]
Looks good.

**Pull request merged**
